services:
  - type: web
    name: video-calling-backend
    env: java
    plan: free
    buildCommand: ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: PORT
        value: 8080 